# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(581, 431)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.drawCanvas = QtWidgets.QFrame(Form)
        self.drawCanvas.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.drawCanvas.setFrameShadow(QtWidgets.QFrame.Raised)
        self.drawCanvas.setObjectName("drawCanvas")
        self.verticalLayout.addWidget(self.drawCanvas)
        self.buttonHolder = QtWidgets.QFrame(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonHolder.sizePolicy().hasHeightForWidth())
        self.buttonHolder.setSizePolicy(sizePolicy)
        self.buttonHolder.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.buttonHolder.setFrameShadow(QtWidgets.QFrame.Raised)
        self.buttonHolder.setObjectName("buttonHolder")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.buttonHolder)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.drawButton = QtWidgets.QPushButton(self.buttonHolder)
        self.drawButton.setObjectName("drawButton")
        self.verticalLayout_2.addWidget(self.drawButton)
        self.verticalLayout.addWidget(self.buttonHolder)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Рисователь жёлтых кружочков"))
        self.drawButton.setText(_translate("Form", "Summon da circle"))
