# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(797, 565)
        Form.setStyleSheet("* {\n"
"    background-color: #3DB2FF;\n"
"}\n"
"\n"
"QPushButton {\n"
"    border: 2px solid #CC2936;\n"
"    background-color: #EEE5E9;\n"
"    border-radius: 10%;\n"
"}\n"
"\n"
"QTableView {\n"
"    selection-background-color: red;\n"
"    background-color: #006EB8;\n"
"    color: #EEE5E9;\n"
"}\n"
"\n"
"QPushButton::hover { background-color: #D7C1CB }\n"
"QPushButton:pressed { background-color: #88596E }")
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tableWidget = QtWidgets.QTableWidget(Form)
        self.tableWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.verticalLayout.addWidget(self.tableWidget)
        self.buttonHolder = QtWidgets.QFrame(Form)
        self.buttonHolder.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.buttonHolder.setFrameShadow(QtWidgets.QFrame.Raised)
        self.buttonHolder.setObjectName("buttonHolder")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.buttonHolder)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.clearButton = QtWidgets.QPushButton(self.buttonHolder)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.clearButton.setFont(font)
        self.clearButton.setObjectName("clearButton")
        self.horizontalLayout.addWidget(self.clearButton)
        self.refreshButton = QtWidgets.QPushButton(self.buttonHolder)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.refreshButton.setFont(font)
        self.refreshButton.setObjectName("refreshButton")
        self.horizontalLayout.addWidget(self.refreshButton)
        self.addButton = QtWidgets.QPushButton(self.buttonHolder)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.addButton.setFont(font)
        self.addButton.setObjectName("addButton")
        self.horizontalLayout.addWidget(self.addButton)
        self.editButton = QtWidgets.QPushButton(self.buttonHolder)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.editButton.setFont(font)
        self.editButton.setObjectName("editButton")
        self.horizontalLayout.addWidget(self.editButton)
        self.verticalLayout.addWidget(self.buttonHolder)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Доступные нам сорта кофе"))
        self.clearButton.setText(_translate("Form", "Clear"))
        self.refreshButton.setText(_translate("Form", "Refresh"))
        self.addButton.setText(_translate("Form", "Add entry"))
        self.editButton.setText(_translate("Form", "Edit entry"))
